title: Jose Demo Webpage
author: Akhil Jose
email: joseakhil55@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a sample webpage hosted on github pages, This is my Demo sample file learning how to utilize github pages.
theme: minima

# social links
twitter_username: akhil007 # DO NOT include the @ character, or else the build will fail!
github_username:  akhil_g # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
